# Generated by Django 5.0.4 on 2024-04-11 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=10)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('zip', models.CharField(max_length=6)),
                ('country', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('ssn', models.CharField(max_length=9)),
                ('annual_income', models.IntegerField()),
                ('occupation', models.CharField(max_length=50)),
                ('is_employed', models.BooleanField()),
                ('employer', models.CharField(max_length=50)),
                ('employer_address', models.TextField()),
                ('is_investor', models.BooleanField()),
                ('investment_amount', models.IntegerField()),
                ('investment_duration', models.IntegerField()),
                ('investment_risk', models.CharField(max_length=50)),
                ('investment_type', models.CharField(max_length=50)),
                ('investment_return', models.IntegerField()),
                ('investment_purpose', models.CharField(max_length=50)),
            ],
        ),
    ]
