# Generated by Django 5.0.4 on 2024-04-12 19:11

import dashboard.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='name',
            new_name='first_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.AddField(
            model_name='profile',
            name='insurance_coverage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='insurance_duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='insurance_type',
            field=models.CharField(default='none', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_insured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='onboarding_step',
            field=models.CharField(choices=[(dashboard.models.OnboardingStep['PERSONAL_INFO'], 'personal_info'), (dashboard.models.OnboardingStep['EMPLOYMENT_INFO'], 'employment_info'), (dashboard.models.OnboardingStep['INVESTMENT_INFO'], 'investment_info'), (dashboard.models.OnboardingStep['COMPLETE'], 'complete')], default=dashboard.models.OnboardingStep['PERSONAL_INFO'], max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='investment_return',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='investment_type',
            field=models.CharField(default='none', max_length=50),
        ),
    ]
