# Generated by Django 5.0.4 on 2024-04-15 20:59

import dashboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "dashboard",
            "0003_alter_profile_address_alter_profile_annual_income_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="onboarding_step",
            field=models.CharField(
                choices=[
                    (dashboard.models.OnboardingStep["PERSONAL_INFO"], "PERSONAL_INFO"),
                    (
                        dashboard.models.OnboardingStep["EMPLOYMENT_INFO"],
                        "EMPLOYMENT_INFO",
                    ),
                    (
                        dashboard.models.OnboardingStep["INVESTMENT_INFO"],
                        "INVESTMENT_INFO",
                    ),
                    (dashboard.models.OnboardingStep["COMPLETE"], "COMPLETE"),
                ],
                default=dashboard.models.OnboardingStep["PERSONAL_INFO"],
                max_length=50,
                null=True,
            ),
        ),
    ]
