# Generated by Django 5.0.4 on 2024-04-15 21:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "account_number",
                    models.CharField(
                        default=models.UUIDField(
                            default=uuid.uuid4,
                            editable=False,
                            unique=True,
                            verbose_name="UUID",
                        ),
                        max_length=50,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "routing_number",
                    models.CharField(
                        default=models.UUIDField(
                            default=uuid.uuid4,
                            editable=False,
                            unique=True,
                            verbose_name="UUID",
                        ),
                        max_length=50,
                        null=True,
                        unique=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("deleted_at", models.DateTimeField(null=True)),
                ("deleted", models.BooleanField(default=False, null=True)),
                ("deleted_reason", models.TextField(null=True)),
                (
                    "account_type",
                    models.CharField(
                        choices=[
                            ("CHECKING", "Checking"),
                            ("SAVINGS", "Savings"),
                            ("MONEY_MARKET", "Money Market"),
                            ("CD", "CD"),
                            ("IRA", "IRA"),
                            ("BROKERAGE", "Brokerage"),
                        ],
                        default="CHECKING",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="account_deleted_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accounts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
