# Generated by Django 5.0.4 on 2024-04-15 21:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="account",
            name="id",
        ),
        migrations.AlterField(
            model_name="account",
            name="account_number",
            field=models.CharField(
                default=models.UUIDField(
                    default=uuid.uuid4, editable=False, unique=True
                ),
                max_length=50,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="account_type",
            field=models.CharField(
                choices=[
                    ("CHECKING", "Checking"),
                    ("SAVINGS", "Savings"),
                    ("MONEY_MARKET", "Money Market"),
                    ("CD", "CD"),
                    ("IRA", "IRA"),
                    ("BROKERAGE", "Brokerage"),
                ],
                default="CHECKING",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="account",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="account",
            name="routing_number",
            field=models.CharField(
                default=models.UUIDField(
                    default=uuid.uuid4, editable=False, unique=True
                ),
                max_length=50,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
