# Generated by Django 5.0.4 on 2024-04-16 16:14

import accounts.models
import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_account_account_number_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Card",
            fields=[
                (
                    "card_number",
                    models.BigIntegerField(
                        default=accounts.models.generate_card_number,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("cvv", models.IntegerField(default=accounts.models.generate_cvv)),
                (
                    "expiration_date",
                    models.DateField(
                        default=datetime.datetime(2028, 4, 16, 16, 14, 6, 407003)
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(null=True)),
                ("deleted", models.BooleanField(default=False, null=True)),
                ("deleted_reason", models.TextField(null=True)),
                (
                    "card_type",
                    models.CharField(
                        choices=[
                            ("CREDIT", "Credit"),
                            ("DEBIT", "Debit"),
                            ("REWARDS", "Rewards"),
                        ],
                        default="DEBIT",
                        max_length=50,
                    ),
                ),
                (
                    "card_provider",
                    models.CharField(
                        choices=[
                            ("VISA", "Visa"),
                            ("MASTERCARD", "Mastercard"),
                            ("AMEX", "American Express"),
                        ],
                        default="VISA",
                        max_length=50,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="card_deleted_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cards",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CreditCard",
            fields=[
                (
                    "card_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="accounts.card",
                    ),
                ),
                (
                    "card_limit",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("payment_due_date", models.DateField()),
                (
                    "minimum_payment",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "amount_due",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
            ],
            bases=("accounts.card",),
        ),
        migrations.CreateModel(
            name="RewardsCard",
            fields=[
                (
                    "creditcard_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="accounts.creditcard",
                    ),
                ),
                (
                    "rewards",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "rewards_earned",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "rewards_available",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "rewards_used",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("rewards_expiration", models.DateField()),
            ],
            bases=("accounts.creditcard",),
        ),
        migrations.CreateModel(
            name="DebitCard",
            fields=[
                (
                    "card_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="accounts.card",
                    ),
                ),
                (
                    "daily_limit",
                    models.DecimalField(decimal_places=2, default=500.0, max_digits=10),
                ),
                (
                    "weekly_limit",
                    models.DecimalField(
                        decimal_places=2, default=2500.0, max_digits=10
                    ),
                ),
                (
                    "monthly_limit",
                    models.DecimalField(
                        decimal_places=2, default=8000.0, max_digits=10
                    ),
                ),
                (
                    "transaction_limit",
                    models.DecimalField(
                        decimal_places=2, default=10000.0, max_digits=10
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="debit_cards",
                        to="accounts.account",
                    ),
                ),
            ],
            bases=("accounts.card",),
        ),
    ]
